# Worksheet 04

Name:  Quan Ho

UID: U17207751

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

p: The type of distance metric, it controls the order of distance calculation expoenentially, and it is a real number.

d: The number of dimensions, it represents the number of features or attributes in the data.

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

The Euclidean metric, denoted as L2 distance, is utilized to compute the distance between two points across n dimensions. When p = 2, it signifies the shortest path's length between the points within Euclidean space.

The Manhattan metric, known as L1 distance, is determined by summing the absolute differences between the coordinates of the points across each dimension, with p = 1.









Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

It will be more sensitive to the largest difference in dimension.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No, because it will go agaist the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

When I am assessing documents or text for similarity, particularly when focusing on the angle between vectors. Basically any example where the angle between vectors is prioritized.

f) what does the jaccard distance account for that the manhattan distance doesn't?

It account for the intersesction and it takes the direction and magnitude of differences along each dimension which manhattan does not.

#### Part 2

Consider the following two sentences:

In [66]:
s1 = "hello my name is Alice"
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [67]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [68]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'is', 'my', 'Bob', 'Alice', 'name']
[1, 1, 1, 0, 1, 1]


Let's add a new sentence to our corpus:

In [69]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [70]:
corpus = [s1, s2,s3]
all_words = list(set([item for x in corpus for item in x.split()]))
all_words

['hello', 'is', 'my', 'Bob', 'Claude', 'hi', 'Alice', 'name']

b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [71]:
v1 = [1 if x in s1 else 0 for x in all_words]

v2 = [1 if x in s2 else 0 for x in all_words]

v3 = [1 if x in s3 else 0 for x in all_words]

print("v1:", ''.join(map(str, v1)))
print("v2:", ''.join(map(str, v2)))
print("v3:", ''.join(map(str, v3)))



v1: 11100011
v2: 11110001
v3: 01101101


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [72]:
import numpy as np

def mikowski(vector1, vector2, p):
    return np.sum(np.abs(np.array(vector1) - np.array(vector2)) ** p) ** (1 / p)

def manhattan(vector1, vector2):
    return mikowski(vector1, vector2, 1)

v1 = np.array(v1)
v2 = np.array(v2)
v3 = np.array(v3)

print(manhattan(v1, v2))
print(manhattan(v2, v3))
print(manhattan(v1, v3))
print(v1)
print(v2)
print(v3)


2.0
4.0
4.0
[1 1 1 0 0 0 1 1]
[1 1 1 1 0 0 0 1]
[0 1 1 0 1 1 0 1]


"hello my name is Alice" and "hello my name is Bob"

d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [73]:
all_words = ["hello", "my", "name", "is", "Alice", "Bob", "Claude", "hi"]
v1 = [1 if x in s1 else 0 for x in all_words]

v2 = [1 if x in s2 else 0 for x in all_words]

v3 = [1 if x in s3 else 0 for x in all_words]
v4, v5, v6, v7, v8 = [
    [0,1,0,0,0,1,0,0],
    [1,0,1,0,0,0,0,0],
    [0,0,1,1,0,0,1,1],
    [0,1,1,1,1,1,0,0],
    [1,0,0,0,0,0,0,1]
]

matrix = [v1,v2,v3,v4,v5,v6,v7,v8]

print(all_words)
matrix


['hello', 'my', 'name', 'is', 'Alice', 'Bob', 'Claude', 'hi']


[[1, 1, 1, 1, 1, 0, 0, 0],
 [1, 1, 1, 1, 0, 1, 0, 0],
 [0, 1, 1, 1, 0, 0, 1, 1],
 [0, 1, 0, 0, 0, 1, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 1, 1],
 [0, 1, 1, 1, 1, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1]]

e) How many rows and columns does this matrix have?

In [74]:
print('Number of rows:', len(matrix))
print('Number of columns:', len(matrix[0]))

Number of rows: 8
Number of columns: 8


f) When using the Manhattan distance, which two sentences are the most similar?

In [75]:
min_distance = 100000
for i in range(7):
    for j in range(i+1,8):
        dis = manhattan(matrix[i],matrix[j])
        if dis <= min_distance:
            print(i, ' ',j, ' ', dis)
            min_distance = dis

0   1   2.0
0   6   2.0
1   6   2.0
2   5   1.0


s1: "hello my name is Alice" and s2: "hello my name is Bob" are the most similiar. Other sentences with identical similarity scores include s3 and s7, as well as s5 and s8.